Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 100
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
