name: Test Go
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.25-alpine
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        run: apk add --no-cache imagemagick-dev pkgconf gcc musl-dev
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
